# Данная сборка нужна исключительно для локальной проверки,
# в продакшн среде подъём приложения будет осуществляться за счёт kubernetes ресурсов и чартов Helm.
services:
  db:
    container_name: manager_db
    image: postgres:17-alpine
    volumes:
      - ./data_value:/var/lib/postgresql/data/
    env_file:
      - .env
    #    ports:
    #      - "5432:5432" # Для локального тестового подключения и дебага.
    networks:
      rlg_network:
        ipv4_address: 172.25.0.3

  redis:
    container_name: line_redis
    image: "redis:alpine"
    #    ports:
    #      - "6379:6379" # Для локального тестового подключения и дебага.
    volumes:
      - ./redis-data:/data
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    env_file:
      - .env
    networks:
      rlg_network:
        ipv4_address: 172.25.0.4

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: bet_rabbitmq
    #    ports:
    #      - "5672:5672" # Порт для взаимодействия с RabbitMQ на локальном стенде.
    #      - "15672:15672" # Порт для доступа к панели управления RabbitMQ, в тестовых целях оставлены дефолтные параметры подключения.
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: always
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    networks:
      rlg_network:
        ipv4_address: 172.25.0.5

  bet_maker:
    container_name: bet_maker
    build: bet_maker/.
    ports:
      - "8000:8000" # Порт открыт исключительно в тестовых целях, для проверки эндпоинтов через API интерфейс!
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - db
    networks:
      rlg_network:
        ipv4_address: 172.25.0.6


  line_provider:
    container_name: line_provider
    build: line_provider/.
    ports:
      - "8001:8000" # Порт открыт исключительно в тестовых целях, для проверки эндпоинтов через API интерфейс!
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - redis
    networks:
      rlg_network:
        ipv4_address: 172.25.0.7

networks:
  rlg_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16

volumes:
  data_value:
  rabbitmq:
  redis-data: