"""Comment

Revision ID: 01
Revises: 
Create Date: 2025-01-17 19:24:01.866488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=False, comment='Никнейм пользователя'),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('create_date', sa.BigInteger(), server_default=sa.text('EXTRACT(epoch FROM now())'), nullable=False),
    sa.Column('update_date', sa.BigInteger(), server_default=sa.text('EXTRACT(epoch FROM now())'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('bets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bet_amount', sa.Float(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'Ставка ещё не сыграла.'"), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ID Аккаунта'),
    sa.Column('create_date', sa.BigInteger(), server_default=sa.text('EXTRACT(epoch FROM now())'), nullable=False),
    sa.Column('update_date', sa.BigInteger(), server_default=sa.text('EXTRACT(epoch FROM now())'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bets_id'), 'bets', ['id'], unique=False)
    op.create_index(op.f('ix_bets_user_id'), 'bets', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bets_user_id'), table_name='bets')
    op.drop_index(op.f('ix_bets_id'), table_name='bets')
    op.drop_table('bets')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
